service: serverless-app
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

# you can add statements to the Lambda function's IAM Role here
#  iam:
#    role:
#      statements:
#        - Effect: "Allow"
#          Action:
#            - "s3:ListBucket"
#          Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#        - Effect: "Allow"
#          Action:
#            - "s3:PutObject"
#          Resource:
#            Fn::Join:
#              - ""
#              - - "arn:aws:s3:::"
#                - "Ref" : "ServerlessDeploymentBucket"
#                - "/*"

plugins:
  - serverless-offline

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /hello/{name}
          method: get
